import type { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { gql } from "@apollo/client";
import client from '../apollo-client'

const Home: NextPage = ({ countries }) => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 >
          Welcome to Next.js GraphQL
        </h1>
        <p >
          Demo
        </p>

        <div>
          <ul>
            {countries.map(({ name }: { name: String }) => <li key={name}>{name}</li>)}
          </ul>
        </div>
      </main>

      <footer >
        Demo Footer
      </footer>
    </div>
  )
}



export const getServerSideProps: GetServerSideProps = async function () {
  const { data } = await client.query({
    query: gql`
      query Countries {
        countries {
          code
          name
          emoji
        }
      }
    `,
  });

  return {
    props: {
      countries: data.countries.slice(0, 4),
    },
  };
}

export default Home
